[package]
name = "streamflow-timelock"
version = "0.3.0"
homepage = "https://streamflow.finance"
description = "Timelock crate for Solana programs"
authors = ["Ivan Jelincic <parazyd@dyne.org>, imprfekt <imprfekt@icloud.com>"]
repository = "https://github.com/streamflow-finance/timelock-crate"
readme = "README.md"
license = "AGPL-3.0-only"
edition = "2018"
exclude = [
    "misc/*",
    ".github/*"
]

[dependencies]
borsh = "0.9.1"
solana-program = "1.7.11"
spl-associated-token-account = "1.0.3"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }

#[dev-dependencies]
#solana-program-test = "1.7.14"
#solana-client = "1.7.14"
#solana-sdk = "1.7.14"

[lib]
crate-type = ["cdylib", "lib"]
