[package]
name = "streamflow-timelock"
version = "0.1.0"
homepage = "https://streamflow.finance"
description = "Timelock crate for Solana programs"
authors = ["Ivan Jelincic <parazyd@dyne.org>"]
repository = "https://github.com/streamflow-finance/streamflow-timelock"
readme = "README.md"
license = "AGPL-3.0-only"
edition = "2018"

[dependencies]
bincode = "1.3.3"
serde = "1.0.130"
solana-program = "1.7.12"
spl-associated-token-account = "1.0.3"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }

#[dev-dependencies]
#solana-program-test = "1.7.12"
#solana-client = "1.7.12"
#solana-sdk = "1.7.12"

[lib]
crate-type = ["cdylib", "lib"]
